services:
  db:
    image: mysql:latest
    container_name: sqldatabase
    ports:
      - "8088:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=maxmule
      - MYSQL_DATABASE=itemsDatabase
    volumes:
      - C:/Users/Faraan/Documents/itemsDatabase/db:/var/lib/mysql 